/* create database */
CREATE DATABASE DATA_SHARE;
CREATE SCHEMA POC;
USE DATABASE DATA_SHARE;
USE SCHEMA POC;

/* create roles */
CREATE DATABASE ROLE share_role1;
CREATE DATABASE ROLE share_role2;

/* create objects */
CREATE TABLE DEMO_TABLE(ID INTEGER,NAME STRING);
CREATE SECURE VIEW DEMO_VIEW AS SELECT * FROM DEMO_TABLE;

/*grant privileges to the role1*/
GRANT USAGE ON SCHEMA DATA_SHARE.POC TO DATABASE ROLE DATA_SHARE.share_role1;
GRANT SELECT ON VIEW DATA_SHARE.POC.DEMO_VIEW TO DATABASE ROLE DATA_SHARE.share_role1;

/*grant privileges to the role2*/
GRANT USAGE ON SCHEMA DATA_SHARE.POC TO DATABASE ROLE DATA_SHARE.share_role2;
GRANT SELECT ON VIEW DATA_SHARE.POC.DEMO_VIEW TO DATABASE ROLE DATA_SHARE.share_role2;

/*create share*/
CREATE SHARE DEMO_SHARE;

/*GRANT PERMISSIONS*/
GRANT USAGE ON DATABASE DATA_SHARE TO SHARE DEMO_SHARE;
GRANT DATABASE ROLE DATA_SHARE.share_role1 TO SHARE DEMO_SHARE;
GRANT DATABASE ROLE DATA_SHARE.share_role2 TO SHARE DEMO_SHARE;

/*SHARE WITH PROVIDERS */
ALTER SHARE DEMO_SHARE ADD ACCOUNTS = org1.consumer1,org1.consumer2;


/* CREATE DIRECT SHARE */

/* Create share */
USE ROLE ACCOUNTADMIN;
CREATE SHARE POC_SHARE;

/* Grant permissions */
GRANT USAGE ON DATABASE DATA_SHARE TO SHARE POC_SHARE;
GRANT USAGE ON SCHEMA DATA_SHARE.POC TO SHARE POC_SHARE;
GRANT SELECT ON TABLE DEMO_TABLE TO SHARE POC_SHARE;

/* Share with consumers as direct share */
ALTER SHARE POC_SHARE ADD ACCOUNTS=abc12345,pq67890; --share with Snowflake accounts


/* Create user using SYSADMIN or ACCOUNTADMIN */
CREATE MANAGED ACCOUNT consumer_reader 
ADMIN_NAME = reader_account , ADMIN_PASSWORD = 'Demo123' , TYPE = READER;

/* view existing reader accounts */
SHOW MANAGED ACCOUNTS;

/* DATA CLONING */

/* Create a UAT environment with clone from PROD database*/
CREATE DATABASE RETAIL_DB_CLONE CLONE RETAIL_DB;

/* Create DEV clone from PROD database for data based on the AT clause and taking snapshot */
CREATE TABLE SALES_DB_CLONE CLONE SALES_DB
AT (TIMESTAMP => TO_TIMESTAMP_TZ('04/09/2024 11:10:34', 'mm/dd/yyyy hh24:mi:ss'));

 /* QUERY TABLE_STORAGE_METRICS USAGE VIEW*/
SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.TABLE_STORAGE_METRICS;

